# Generated by Django 5.2 on 2025-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_pergunta_resposta_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('imagem', models.URLField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
