# Generated by Django 5.2 on 2025-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(upload_to='livros/'),
        ),
    ]
