# Generated by Django 5.2 on 2025-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_categoria_imagem_alter_livro_imagem_alter_perfil_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='vendas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
