# Generated by Django 5.2 on 2025-04-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_livro_recomendado_livro_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.URLField(default='https://example.com/default_image.jpg'),
            preserve_default=False,
        ),
    ]
