# Generated by Django 5.2 on 2025-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_pessoa',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1),
        ),
    ]
