# Generated by Django 5.2 on 2025-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_perfil_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_pessoa',
            field=models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1),
        ),
    ]
