name: Build and deploy Python app to Azure Web App - PaginaViradaStore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment to force SQLite in CI
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Run database migrations
        run: python manage.py migrate

      - name: Start Django server in background
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress
        run: |
          npm install
          npx cypress install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Clean testing files
        run: |
          rm -f db.sqlite3
          rm -f .env

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7671980A78945C4AB4423910CA31EF2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D66C1E62D9244683B21C79DDF2427544 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CFF844993964C54A287DE8F8B7D32C4 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'PaginaViradaStore'
          slot-name: 'Production'
          package: release.zip
