name: Build and Test Django App with Cypress

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variable for CI
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SQLite database and run migrations
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Start Django server in background
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies and Cypress
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Clean up test artifacts
        run: |
          rm -f db.sqlite3
          rm -f ci_db.sqlite3
          rm -f .env

      - name: Archive Cypress screenshots (if any failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Archive project zip for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
