name: Build and Deploy Django + Cypress

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtualenv and install Python deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress and JS deps
        run: |
          npm ci
          npx cypress install
          chmod +x node_modules/.bin/cypress

      - name: Run migrations and local server
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: Run Cypress tests
        run: |
          npx cypress run

      - name: Clean test/development files
        run: |
          rm -f .env db.sqlite3 cypress.config.js package-lock.json package.json
          rm -rf cypress node_modules venv

      - name: Zip for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC2CFEEC6D90471A9A7D1DE1AFDA7381 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D01DBB11DCD843DCB2F7455C0DC81599 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC5273913AE940BA8A7E479B70ED94DB }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'advocatusonline'
          slot-name: 'Production'
