name: Build and deploy Python app to Azure Web App - PaginaVirada-Store

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r Pagina_Virada_Store/requirements.txt

      - name: Cleaning testing files
        run: |
          cd Pagina_Virada_Store/
          rm -f db.sqlite3
          rm -f .env
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd Pagina_Virada_Store/
          zip release.zip ./* -r
          cd ..
          mv Pagina_Virada_Store/release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C442F6513AEB45E6AED03D19D0EEEF44 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87E0BEA48086402ABFE9D2039C21405C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_94080A1CD55F454181515D4E6A3FBF9F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'PaginaVirada-Store'
          slot-name: 'Production'
          package: release.zip
