name: Rodar Testes Cypress

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aplicar migrações do Django
        run: |
          python manage.py migrate

      - name: Iniciar servidor Django em segundo plano
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
        env:
          DJANGO_SETTINGS_MODULE: seu_projeto.settings  # troque pelo nome do seu módulo de settings

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências do Cypress
        run: npm install
        working-directory: e2e/cypress  # ajuste se o package.json estiver em outro lugar

      - name: Aguardar o servidor iniciar
        run: |
          sleep 10  # pode ajustar se necessário
          curl -sSf http://localhost:8000

      - name: Rodar testes Cypress
        run: npx cypress run
        working-directory: e2e/cypress
