name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: dev  # Garante uso do SQLite (e não PostgreSQL)

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aplicar migrações do Django
        run: python manage.py migrate

      - name: Rodar testes Django
        run: python manage.py test

      - name: Instalar dependências do Cypress
        run: npm install

      - name: Rodar testes Cypress
        run: npx cypress run
        working-directory: ./e2e/cypress
