name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          # Instalar as dependências Python
          pip install -r requirements.txt
          # Instalar as dependências do Cypress (Node.js)
          npm ci

      - name: Run migrations
        run: python manage.py migrate

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Run Cypress tests
        run: |
          # Rodar os testes Cypress
          npx cypress run

      - name: Clean testing files
        run: |
          # Limpar arquivos de testes
          rm -f db.sqlite3
          rm -f .env
